apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-nginx
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology-nginx
  template:
    metadata:
      labels:
        app: netology-nginx
    spec:
      containers:
        - name: nginx
          image: cr.yandex/crp602u6ka42e2m3tmst/netology-nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netology-nginx
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: netology-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
