name: Terraform CI/CD (infra)

on:
  pull_request:
    paths:
      - "terraform/infra/**"
  push:
    branches: [ "main", "master" ]
    paths:
      - "terraform/infra/**"

concurrency:
  group: terraform-infra
  cancel-in-progress: false

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
  TF_VAR_sa_key_file: ${{ github.workspace }}/key.json
  TF_VAR_vm_name: ${{ secrets.TF_VAR_vm_name }}
  TF_VAR_subnet_name: ${{ secrets.TF_VAR_subnet_name }}
  TF_VAR_metadata: ${{ secrets.TF_VAR_metadata }}

  # Yandex provider
  YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  YC_SERVICE_ACCOUNT_KEY_FILE: ${{ github.workspace }}/key.json

  # Object Storage
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Write YC SA key
        run: |
          echo '${{ secrets.YC_SA_KEY_JSON }}' > ${{ github.workspace }}/key.json

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -no-color
